/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.redplugins.cash;

import org.bukkit.Bukkit;
import org.bukkit.plugin.java.JavaPlugin;

import io.github.redplugins.cash.commands.CashCommand;
import io.github.redplugins.cash.database.Mysql;
import io.github.redplugins.cash.manager.JoinEvent;

public class Cash extends JavaPlugin {
    
	private Mysql Mysql = new Mysql();
	
	public void onEnable() {
		registerCommands();
		registerListeners();
		Mysql.initialize();
	}
	
	public void onDisable() {
		Mysql.closeConnection();
	}
	
	void registerCommands() {
		getCommand("cash").setExecutor(new CashCommand());
	}
	
	void registerListeners() {
		Bukkit.getPluginManager().registerEvents(new JoinEvent(), this);
	}
	
	public static Cash getInstance() { return getPlugin(Cash.class); }
}
